#!/usr/bin/env bash

# Install Nginx if not already installed
apt-get update
apt-get -y install nginx

# Allow Nginx HTTP traffic
ufw allow 'Nginx HTTP'

# Create a configuration file for the redirection
cat > /etc/nginx/sites-available/redirect_me <<EOF
server {
    listen 80;
    listen [::]:80;

    server_name _;

    location /redirect_me {
        return 301 http://github.com/BlessKobby;
    }

    # Additional server configuration goes here
}
EOF

# Create a symbolic link to enable the site
ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration and restart the service
nginx -t
service nginx restart
